# Site
site_name: Athena 文档站
site_url: https://athena.mkc.icu/

# Repo
repo_url: https://github.com/HydroGest/AthenaDocsNG
repo_name: HydroGest/AthenaDocsNG
edit_uri: edit/main/docs/

nav:
  - 首页: /index
  - 用户手册: 
    - 快速上手: /user-guide/getting-started
    - 从 V1 迁移: /user-guide/migrate-from-v1
    - 配置: 
      - 记忆槽位设置: /user-guide/configuration/memory-slot
      - 主 API 配置: /user-guide/configuration/main-api
      - API 参数配置: /user-guide/configuration/parameters
      - Prompt 配置: /user-guide/configuration/prompt
      - Bot 设定: /user-guide/configuration/bot-settings
      - 验证器设置: /user-guide/configuration/verifier
    - 教程: /index
     

# Theme
theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.progress
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: 切换到浅色模式
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: 切换到深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: 跟随系统

# Markdown Extensions
markdown_extensions: 
  - attr_list
  - md_in_html
  - def_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_javascript:
  - javascripts/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

extra_css:
  - stylesheets/extra.css
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css